### ISSUE TITLE
2.2.0.8 is not loading images

### ISSUE THREAD

**Issue by k3v3n** [easingslider/easing-slider#15]
Since 2.2.0.7, images are not loading in the slider edit page. 2.2.0.7 work's fine. 
I tried 2.2.0.8 without plugins and default twentyfifteen and it doesn't load images.

**Comment by MatthewRuddy** [comment]
Hey k3v3n, could you link me to your site? I'll take a quick look for you.

**Comment by k3v3n** [comment]
Hi Matthew, 

I cannot provide you a link to the website because revert back to 2.2.0.7 and it worked perfectly. 

There’s is really a problem with the latest version. Did you tried 2.2.0.8 on a fresh WordPress install?
I tried it and it didn’t worked. 

I tried to look at your latest commit in version 2.2.0.8 but I didn’t have much time to check it out in deep. 

BTW. Nice work for the upgrade to 2.0 version. 

Best regards.

**Comment by MatthewRuddy** [comment]
Hi Kevin, yes of course I did. I test all versions on a fresh install, various PHP versions and multiple themes. I've tested it thoroughly and it works - you're experiencing an isolated issue by the sound of things possibly due to your theme or a conflict with another plugin.

Disable all the other plugins you have active, and check if the issue persists. Also try changing your theme temporarily to check for theme conflicts.

If you're experiencing issues with Easing Slider as the only active plugin, and the default WordPress theme, then there has likely been a settings conflict or an error. Use Google Chrome's "Web Inspector" tool to check for console errors, and report them back to me.

If you can still link to your site, despite using v2.2.0.7 of Easing Slider, I can still check to see if I can notice anything unusual.

**Comment by k3v3n** [comment]
Thanks for the follow-up. That’s appreciated. 

I’ve check out the console and there was no JavaScript error. 

I did tried with an other fresh install from a Plesk Panel server and it did work correctly. 

I think that the problem might  come from database records.

**Comment by MatthewRuddy** [comment]
Ok. Going to close this topic but feel free to re-open it if needed or if you come across any issues that we can fix :)
